services:
  - type: web
    name: weather-backend
    env: docker
    plan: free
    region: ohio
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: REDIS_URL
        fromService:
          name: cache-redis
          type: redis
          property: connectionString
      - key: OPENWEATHER_API_KEY
        sync: false # Set this in the Render dashboard manually for security
      - key: DATABASE_URL
        fromService:
          name: weather-db
          type: database
          property: connectionString
      - key: DB_DRIVER
        value: org.postgresql.Driver
      - key: DB_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect

  - type: redis
    name: cache-redis
    plan: free
    region: ohio
    ipAllowList: [] # Allow internal traffic only

databases:
  - name: weather-db
    plan: free
    region: ohio
